@startsalt abrirInvestigador-wireframe
{
    ====
    <b>GIPF - PERFIL DE INVESTIGADOR</b>
    ====
    {
        <b>Detalles del investigador</b>
        --
        {
            {<b>ID:</b>         | "INV-045"}
            {<b>Nombre:</b>     | "Ana"}
            {<b>Apellido:</b>   | "García López"}
            {<b>Campo:</b>      | "Inteligencia Artificial"}
            {<b>DNI:</b>        | "12345678X"}
            {<b>Carrera:</b>    | "Ingeniería Informática"}
            {<b>Máster:</b>     | "Ciencia de Datos"}
        }

        ~~

        {[Editar perfil] | [Volver ]}
    }
}
@endsalt
