@startuml abrirProyectos
skinparam linetype polyline

state in1 as "PANEL_PRINCIPAL_ABIERTO"
in1 -[#green]-> abrirProyectos

state in2 as "PROYECTO_ABIERTO"
in2 -[#green]-> abrirProyectos

state in3 as "INVESTIGADOR_ABIERTO"
in3 -[#green]-> abrirProyectos
note on link
abrirProyectos(ID)
end note


state abrirProyectos as "abrirProyectos()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista
    note on link
    <b>Coordinador</b> solicita abrir listado de proyectos
    end note

    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta un listado de proyectos de investigación/del investigador
    • ID
    • Título
    • Estado del proyecto
    • Coordinador responsable
    • Fechas de inicio y fin
    • Descripción
    
    • Permite filtrar y buscar proyectos

    <b>Regla de presentación del listado:</b>
    • Si se accede desde PANEL_PRINCIPAL_ABIERTO o PROYECTO_ABIERTO:
    se muestra el listado global de proyectos
    • Si se accede desde INVESTIGADOR_ABIERTO:
    se muestran únicamente los proyectos asociados al investigador
    end note

    FiltrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Coordinador</b> filtra o busca proyectos
    <b>Sistema</b> actualiza el listado
    end note

    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Coordinador</b> selecciona una opción de navegación
    end note

    MostrandoLista -[#green]-> [*]
    note on link
    <b>Coordinador</b> selecciona una opción de navegación
    end note
}

abrirProyectos -[#green]-> PROYECTOS_ABIERTOS
note on link
Listado de proyectos visible
end note

abrirProyectos -[#green]-> PROYECTO_ABIERTO
note on link
abrirProyecto()
end note

abrirProyectos -[#green]-> PROYECTO_ABIERTO
note on link
crearProyecto()
end note

abrirProyectos -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
abrirPanelPrincipal()
end note

@enduml
