@startuml abrirPerfil

skinparam linetype polyline

state abrirPerfil as "abrirPerfil()" {

    state " " as MostrandoPerfil
    state " " as OpcionSelecionado

    [*] -[#green]-> MostrandoPerfil 
    note on link
    <b>Investigador</b> solicita ver su perfil
    end note    
    
    MostrandoPerfil -[#green]-> OpcionSelecionado
    note on link
    <b>Sistema</b> presenta el perfil
    • ID, nombre, apellido, proyectos activos
    • Permite solicitar editar opciones de perfil
    • Permite solicitar editar carga de trabajo
    • Permite solicitar ver una lista de investigadores
    • Permite solicitar ver todos los proyectos
    • Permite solicitar ver las publicaciones hechas por el investigador
    • Permite solicitar ver las publicaciones hechas por otros investigadores
    end note
    
    OpcionSelecionado -[#green]-> [*]
    note on link
      <b>Investigador</b> selecciona una de las opciones
    end note
    
}

abrirPerfil -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
abrirOpcionesPerfil()
end note

abrirPerfil -[#green]-> OPCIONES_CARGA_TRABAJO_ABIERTAS
note on link
abrirOpcionesCargaTrabajo()
end note

abrirPerfil -[#green]-> INVESTIGADORES_ABIERTOS
note on link
abrirInvestigadores()
end note

abrirPerfil -[#green]-> PROYECTOS_ABIERTOS
note on link
abrirProyectos()
end note

abrirPerfil -[#green]-> MIS_PUBLICACIONES_ABIERTAS
note on link
abrirMisPublicaciones()
end note

abrirPerfil -[#green]-> PUBLICACIONES_ABIERTAS
note on link
abrirPublicaciones()
end note

@enduml
