@startuml verPerfil

skinparam linetype polyline

state verPerfil as "verPerfil()" {

    state " " as MostrandoPerfil
    state " " as OpcionSelecionado

    [*] -[#green]-> MostrandoPerfil 
    note on link
    <b>Investigador</b> solicita ver Perfil
    end note    
    
    MostrandoPerfil -[#green]-> OpcionSelecionada
    note on link
    <b>Sistema</b> presenta el perfil
    • ID, nombre, apellido, proyectos activos
    • Permite solicitar editar opciones de perfil
    • Permite solicitar editar carga de trabajo
    end note
    
    OpcionSelecionada -[#green]-> [*]
    note on link
      <b>Investigador</b> selecciona una de las opciones
    end note
    
}

verPerfil -[#green]-> OPCIONES_PERFIL_ABIERTO
note on link
abrirOpcionesPerfil()
end note

verPerfil -[#green]-> OPCIONES_CARGA_TRABAJO_ABIERTAS
note on link
abrirOpcionesCargaTrabajo()
end note

@enduml
