@startuml CDUCoordinador

title Casos de uso para el actor "Coordinador"

left to right direction

actor "Coordinador" as coordinador


package "Gestión de proyectos" {
    usecase crearProyecto as "crearProyecto()"
    usecase abrirProyecto as "abrirProyecto()"
    usecase editarProyecto as "editarProyecto()"
    usecase eliminarProyecto as "eliminarProyecto()"
}

package "Gestión de investigadores" {
    usecase agregarInvestigador as "agregarInvestigador()"
    usecase verInvestigadores as "verInvestigadores()"
    usecase modificarInvestigador as "modificarInvestigador()"
    usecase eliminarInvestigador as "eliminarInvestigador()"
}

package "Convocatorias" {
    usecase buscarConvocatoria as "buscarConvocatoria()"
    usecase analizarConvocatoria as "analizarConvocatoria()"
}

package "Propuesta" {
    usecase elaborarPropuesta as "elaborarPropuesta()"
    usecase presentarPropuesta as "presentarPropuesta()"
}


coordinador --> (crearProyecto)
coordinador --> (abrirProyecto)
coordinador --> (editarProyecto)
coordinador --> (eliminarProyecto)

(agregarInvestigador) <-- coordinador
(verInvestigadores) <-- coordinador
(modificarInvestigador) <-- coordinador
(eliminarInvestigador) <-- coordinador


(buscarConvocatoria) <-- coordinador
(analizarConvocatoria) <-- coordinador

coordinador --> (elaborarPropuesta)
coordinador --> (presentarPropuesta)

@enduml