@startuml DiagramaContextoCoordinador

left to right direction


[*] --> SESION_CERRADA
SESION_CERRADA --> SESION_CERRADA: denegarInicioSesion()
SESION_CERRADA --> PERFIL: iniciarSesion()
PERFIL --> SESION_CERRADA: cerrarSesion()


PERFIL --> OPCIONES_PERFIL: abrirOpcionesPerfil()
PERFIL --> OPCIONES_CARGA_TRABAJO: abrirOpcionesCargaTrabajo()
PERFIL --> PROYECTOS_ABIERTOS: abrirProyectos()
PERFIL --> INVESTIGADORES_ABIERTOS: abrirInvestigadores()


OPCIONES_PERFIL --> OPCIONES_PERFIL: editarNombre()
OPCIONES_PERFIL --> OPCIONES_PERFIL: editarApellido()
OPCIONES_PERFIL --> OPCIONES_PERFIL: editarId()
OPCIONES_PERFIL --> OPCIONES_PERFIL: editarCarrera()
OPCIONES_PERFIL --> OPCIONES_PERFIL: editarMaster()
OPCIONES_PERFIL --> OPCIONES_PERFIL: editarDni()
OPCIONES_PERFIL --> SESION_CERRADA: eliminarPerfil()




OPCIONES_CARGA_TRABAJO --> OPCIONES_CARGA_TRABAJO: editarHorasClase()
OPCIONES_CARGA_TRABAJO --> OPCIONES_CARGA_TRABAJO: editarHorasInvestigacion()



PROYECTOS_ABIERTOS --> PROYECTO_ABIERTO: abrirProyecto()
PROYECTOS_ABIERTOS --> PROYECTO_ABIERTO: crearProyecto()

PROYECTO_ABIERTO --> PROYECTO_ABIERTO: editarNombreProyecto()
PROYECTO_ABIERTO --> PROYECTO_ABIERTO: editarDescripcionProyecto()
PROYECTO_ABIERTO --> PROYECTO_ABIERTO: editarFechaLimiteProyecto()
PROYECTO_ABIERTO --> PROYECTOS_ABIERTOS: eliminarProyecto()
PROYECTO_ABIERTO --> PROYECTO_ABIERTO: agregarInvestigador()
PROYECTO_ABIERTO --> PROYECTO_ABIERTO: eliminarInvestigador()


PROYECTO_ABIERTO --> ENTREGABLES_ABIERTOS: abirEntregables()
PROYECTO_ABIERTO --> ENTREGABLES_ABIERTOS: crearEntregable()
ENTREGABLES_ABIERTOS --> ENTREGABLES_ABIERTOS: editarDescripcionEntregable()
ENTREGABLES_ABIERTOS --> PROYECTO_ABIERTO: eliminarEntregable()


PROYECTO_ABIERTO --> INVESTIGADORES_ABIERTOS: abrirInvestigadores()

INVESTIGADORES_ABIERTOS --> INVESTIGADOR_ABIERTO: abrirInvestigador()
INVESTIGADORES_ABIERTOS --> INVESTIGADOR_ABIERTO: crearInvestigador()


INVESTIGADOR_ABIERTO --> OPCIONES_PERFIL: abrirOpcionesPerfil()














@enduml