@startuml eliminarPublicacion
skinparam linetype polyline

state in1 as "MI_PUBLICACION_ABIERTA"
in1 -[#green]-> eliminarPublicacion

state eliminarPublicacion as "eliminarPublicacion()" {

    state " " as ConfirmandoEliminacion
    state " " as Eliminando

    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Coordinador</b> tiene una publicación propia abierta
    <b>Coordinador</b> solicita eliminar publicación
    end note

    ConfirmandoEliminacion -[#green]-> Eliminando
    note on link
    <b>Sistema</b> solicita confirmación
    <b>Coordinador</b> confirma la eliminación
    end note

    Eliminando -[#green]-> [*]
    note on link
    <b>Sistema</b> elimina la publicación
    <b>Sistema</b> muestra mensaje de éxito
    end note

    ConfirmandoEliminacion -[#red]-> [*]
    note on link
    <b>Coordinador</b> cancela la eliminación
    <b>Sistema</b> no realiza cambios
    end note
}

eliminarPublicacion -[#green]-> MIS_PUBLICACIONES_ABIERTAS
note on link
Publicación eliminada
end note

eliminarPublicacion -[#red]-> MI_PUBLICACION_ABIERTA
note on link
Eliminación cancelada
end note

@enduml
