@startuml crearProyecto

skinparam linetype polyline

PROYECTOS_ABIERTOS -[#green]-> crearProyecto

state crearProyecto as "crearProyecto()" {

    state " " as SolicitandoDatos
    state " " as CreandoProyecto

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Coordinador</b> solicita crear proyecto
    end note

    SolicitandoDatos -[#green]-> CreandoProyecto
    note on link
    <b>Sistema</b> solicita datos del nuevo proyecto
    • ID
    • Título
    • Estado del proyecto
    • Nombre del coordinador
    • Fechas de inicio y fin
    • Descripción
    end note

    CreandoProyecto -[#green]-> [*]
    note on link
    <b>Coordinador</b> proporciona los datos solicitados
    <b>Sistema</b> registra el nuevo proyecto
    end note
}

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
Proyecto creado correctamente
end note

@enduml
