@startuml crearProyecto

skinparam linetype polyline

PROYECTOS_ABIERTOS -[#green]-> crearProyecto

state crearProyecto as "crearProyecto()" {

    state " " as SolicitandoDatos
    state " " as CreandoProyecto

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Coordinador</b> solicita crear proyecto
    end note

    SolicitandoDatos -[#green]-> CreandoProyecto
    note on link
    <b>Sistema</b> solicita datos del nuevo proyecto
    • Título
    • Descripción
    • Fechas
    • Estado
    end note

    CreandoProyecto -[#green]-> [*]
    note on link
    <b>Coordinador</b> proporciona datos
    <b>Sistema</b> crea el proyecto
    end note
}

crearProyecto -[#green]-> PROYECTO_ABIERTO
note on link
proyecto creado
end note

@enduml
