@startuml crearEntregable

skinparam linetype polyline

state crearEntregable as "crearEntregable()" {

    state " " as RellenandoEntregable
    state " " as ValidandoDatos

    [*] -[#green]-> RellenandoEntregable
    note on link
    <b>Investigador</b> solicita crear entregable nuevo
    end note

    RellenandoEntregable -[#green]-> ValidandoDatos
    note on link
    <b>Investigador</b> solicita guardar entregable
    <b>Sistema</b> valida los datos introducidos
    end note

    ValidandoDatos -[#green]-> RellenandoEntregable
    note on link
    Datos del entregable no válidos
    <b>Sistema</b> muestra mensajes de error
    • Campos obligatorios vacíos
    • Fechas incoherentes
    • Formato incorrecto en algún campo
    end note

    ValidandoDatos -[#green]-> [*]
    note on link
    Datos del entregable válidos
    <b>Sistema</b> crea el proyecto
    • Asigna identificador de proyecto
    • Guarda título, descripción, fechas, Investigador
    • Muestra entregable creado
    end note
}

crearEntregable -[#green]-> ENTREGABLES_ABIERTOS
note on link
editarEntregable()
end note

crearEntregable -[#green]-> PROYECTO_ABIERTO
note on link
eliminarEntregable()
end note

crearEntregable -[#green]-> PROYECTO_ABIERTO
note on link
abrirProyecto()
end note

@enduml