@startuml abrirProyecto

skinparam linetype polyline

state abrirProyecto as "abrirProyecto()" {

    state " " as MostrandoListaProyectos
    state " " as SeleccionandoProyecto

    [*] -[#green]-> MostrandoListaProyectos
    note on link
    <b>Coordinador</b> solicita abrir proyectos
    end note

    MostrandoListaProyectos -[#green]-> SeleccionandoProyecto
    note on link
    <b>Sistema</b> presenta lista de proyectos de investigación
    • ID
    • Título
    • Estado del proyecto
    • Nombre del coordinador
    • Fechas de inicio y fin
    • Descripción
    • Permite solicitar filtrar/buscar
    • Permite solicitar abrir un proyecto
    end note

    SeleccionandoProyecto -[#green]-> SeleccionandoProyecto
    note on link
    <b>Coordinador</b> solicita filtrar/buscar proyectos
    <b>Sistema</b> presenta lista filtrada
    end note

    SeleccionandoProyecto -[#green]-> [*]
    note on link
    <b>Coordinador</b> solicita abrir un proyecto de la lista
    end note
}

PROYECTOS_ABIERTOS -[#green]-> abrirProyecto
note on link
abrirProyecto()
end note

ENTREGABLES_ABIERTOS -[#green]-> abrirProyecto
note on link
abrirProyecto()
end note

abrirProyecto -[#green]-> PROYECTO_ABIERTO
note on link
proyecto abierto
end note

@enduml
