@startuml CU_Investigador
title Casos de uso del Investigador / Docente-Investigador

left to right direction
actor "Investigador /\nDocente-Investigador" as Inv

rectangle "Plataforma FUNIBER" {

  rectangle "Gestión de Perfil y Carga" {
    usecase "GestionarPerfil()" as CU_GestionarPerfil
    usecase "VerCargaAcademica()" as CU_VerCarga
    usecase "SolicitarCompensacion()" as CU_SolicitarComp
  }

  rectangle "Participación en Convocatorias" {
    usecase "ConsultarConvocatoriasAsignadas()" as CU_VerConv
  }

  rectangle "Participación en Proyectos" {
    usecase "ConsultarMisProyectos()" as CU_VerProyectos
    usecase "SubirEntregable()" as CU_SubirEntregable
    usecase "VerEstadoEntregable()" as CU_VerEstado
  }

}

Inv --> CU_GestionarPerfil
Inv --> CU_VerCarga
Inv --> CU_SolicitarComp
Inv --> CU_VerConv
Inv --> CU_VerProyectos
Inv --> CU_SubirEntregable
Inv --> CU_VerEstado

@enduml