@startsalt crearProyecto-wireframe
{
    ====
    <b>GIPF - CREAR PROYECTO</b>
    ====
    {
        <b>Datos del proyecto:</b>
        --
        {
            {
            {<b>Título:</b> | [                                      ]}
            --
            {<b>Estado:</b> | { "Borrador" | "En curso" | "Finalizado" }
            --
            <b>Coordinador:</b> | "Nombre del coordinador                 "}
            --
            {<b>Fecha inicio:</b> | [            ]
            --
            <b>Fecha fin:</b> | [            ]}
            --
            {<b>Descripción:</b> |
                {[                                      ]}}
                --
            }
            <i>El ID del proyecto se generará automáticamente</i>
            <i>Tras crearlo, el proyecto se abrirá para continuar su gestión</i>
        }

        ~~

        {[Crear proyecto] | [Cancelar]}
    }
}
@endsalt
