@startuml abrirConvocatoria

skinparam linetype polyline

state abrirConvocatoria as "abrirConvocatoria()" {

    state " " as MostrandoListaConvocatorias
    state " " as SeleccionandoConvocatoria

    [*] -[#green]-> MostrandoListaConvocatorias
    note on link
    <b>Coordinador</b> solicita abrir convocatorias
    end note

    MostrandoListaConvocatorias -[#green]-> SeleccionandoConvocatoria
    note on link
    <b>Sistema</b> presenta lista de convocatorias
    • ID
    • Título
    • Estado de la convocatoria
    • Fecha de inicio y fin
    • Descripción
    • Permite solicitar filtrar/buscar convocatorias
    • Permite solicitar abrir una convocatoria
    end note

    SeleccionandoConvocatoria -[#green]-> SeleccionandoConvocatoria
    note on link
    <b>Coordinador</b> solicita filtrar/buscar convocatorias
    <b>Sistema</b> presenta lista filtrada
    end note

    SeleccionandoConvocatoria -[#green]-> [*]
    note on link
    <b>Coordinador</b> solicita abrir una convocatoria de la lista
    end note
}

CONVOCATORIAS_ABIERTAS -[#green]-> abrirConvocatoria
note on link
abrirConvocatoria()
end note

abrirConvocatoria -[#green]-> CONVOCATORIA_ABIERTA
note on link
Convocatoria abierta
end note

@enduml
