@startuml solicitarEliminacionPerfil

skinparam linetype polyline

state solicitarEliminacionPerfil as "solicitarEliminacionPerfil()" {

    state " " as SeleccionandoPerfil
    state " " as ConfirmandoSolicitud
    state " " as SolicitudEnviada

    [*] -[#green]-> SeleccionandoPerfil
    note on link
    <b>Coordinador</b> solicita la eliminacion de su perfil
    end note

    SeleccionandoPerfil -[#green]-> ConfirmandoSolicitud
    note on link
    <b>Sistema</b> presenta confirmación de solicitud de eliminación
    • Confirmar o cancelar
    end note

    ConfirmandoSolicitud -[#green]-> SolicitudEnviada
    note on link
    <b>Coordinador</b> solicita confirmar eliminación
    <b>Sistema</b> permite confirmar la solicitud de eliminación
    end note

    
    SolicitudEnviada -[#green]-> [*]
   
}


solicitarEliminacionPerfil -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
iniciarSesion()
end note

@enduml
