@startuml DiagramaClasesProyecto

title: Sistema de gestión de proyectos


class Proyecto <<Principal>> #FFAAAA{

}

class Convocatoria{

}

class Propuesta{

}





class InvestigadorDocente{

}

class Coordinador{

}

class Antena{

}

class Colaborador{

}




class EstadoProyecto{

}

class CargaTrabajo{

}

class Entregables{

}

class Recompensa{

}



Convocatoria --|> Propuesta: genera
Propuesta --|> Proyecto: genera

Proyecto --o InvestigadorDocente: está formado por
Proyecto --* EstadoProyecto: tiene
Proyecto --* Entregables: tiene
Proyecto --* CargaTrabajo: genera
Proyecto --* Recompensa: genera

Coordinador --o Proyecto: coordina

Antena --o Convocatoria: busca

Colaborador --o Proyecto: puede participar

InvestigadorDocente --> CargaTrabajo: tiene
InvestigadorDocente --o Proyecto: trabaja en

Recompensa --> InvestigadorDocente: beneficia a

















@enduml