@startuml DiagramaClasesRed

title Sistema de red de investigadores

class InvestigadorDocente <<Principal>> #FFAAAA {
}

class Proyecto {
}

class Coordinador {
}

class CargaTrabajo {
}

class PerfilInvestigador {
}


InvestigadorDocente --> Proyecto : participa en
InvestigadorDocente --> CargaTrabajo : tiene carga asignada
InvestigadorDocente *-- PerfilInvestigador : tiene
InvestigadorDocente --> InvestigadorDocente : interactúa con

Proyecto --> CargaTrabajo : genera

Coordinador --> InvestigadorDocente : recluta

@enduml
