@startuml ConsultarCargaAcademica
title Consultar carga académica
skinparam linetype polyline

state MI_CARGA_TRABAJO_INICIAL as "MI_CARGA_TRABAJO"
state MI_CARGA_TRABAJO_FINAL   as "MI_CARGA_TRABAJO"

MI_CARGA_TRABAJO_INICIAL -[#green]-> consultarCargaAcademica

state consultarCargaAcademica as "consultarCargaAcademica()" {

    state " " as MostrarResumen

    [*] -[#green]-> MostrarResumen
    note on link
    <b>Investigador/Docente-Investigador</b>
    accede a MI_CARGA_TRABAJO desde PERFIL.
    end note

    MostrarResumen -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta un resumen de carga:
    • Horas de docencia planificadas
    • Horas de investigación
    • Proyectos activos/asignados

    En el caso de Docente-Investigador,
    indica si se aproxima al límite
    de 16 h/semana de docencia.
    end note
}

consultarCargaAcademica -[#green]-> MI_CARGA_TRABAJO_FINAL : volverAlPerfil()

@enduml
