@startuml abrirOpcionesCargaTrabajo

skinparam linetype polyline

state abrirOpcionesCargaTrabajo as "abrirOpcionesCargaTrabajo()" {

    state " " as MostrandoEntregable
    state " " as FiltrandoEntregable

    [*] -[#green]-> MostrandoEntregable 
    note on link
    <b>Investigador</b> solicita abrir carga de trabajo
    end note    
    
    MostrandoEntregable -[#green]-> FiltrandoEntregable
    note on link
    <b>Sistema</b> presenta opciones de carga de trabajo
    •<b>Sistema</b> presenta la carga de trabajo del investigador
    • Permite solicitar editar carga de trabajo
    • Permite solicitar abrir el panel principal
    end note
    
    FiltrandoEntregable -[#green]-> [*]
    note on link
    <b>Investigador</b> solicita una de las opciones
    end note
}

abrirOpcionesCargaTrabajo -[#green]-> OPCIONES_CARGA_TRABAJO_ABIERTAS
note on link
editarCargaTrabajo()
end note

abrirOpcionesCargaTrabajo -[#green]-> PANEL_PRINCIPAL_ABIERTO
note on link
abrirPanelPrincipal()
end note

@enduml
