@startuml presentarPropuesta

skinparam linetype polyline

state presentarPropuesta as "presentarPropuesta()" {

    state " " as MostrandoPropuesta
    state " " as ConfirmandoEnvio

    [*] -[#green]-> MostrandoPropuesta
    note on link
    <b>Coordinador</b> tiene una propuesta elaborada
    <b>Coordinador</b> solicita presentar propuesta
    end note

    MostrandoPropuesta -[#green]-> ConfirmandoEnvio
    note on link
    <b>Sistema</b> solicita confirmación
    • ¿Desea presentar la propuesta?
    • La propuesta no podrá modificarse
    end note

    ConfirmandoEnvio -[#red]-> MostrandoPropuesta
    note on link
    <b>Coordinador</b> cancela la presentación
    <b>Sistema</b> mantiene la propuesta sin cambios
    end note

    ConfirmandoEnvio -[#green]-> [*]
    note on link
    <b>Coordinador</b> confirma presentación
    <b>Sistema</b> marca la propuesta como presentada
    end note
}

presentarPropuesta -[#green]-> PROYECTO_ABIERTO
note on link
propuesta presentada
end note

presentarPropuesta -[#green]-> PERFIL
note on link
volver
end note

@enduml
