@startuml buscarConvocatoria

skinparam linetype polyline

state buscarConvocatoria as "buscarConvocatoria()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista
    note on link
    <b>Coordinador</b> solicita buscar convocatorias
    end note

    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta lista de convocatorias
    • Permite solicitar filtrar / buscar
    • Permite seleccionar una convocatoria
    • Permite solicitar analizar convocatoria seleccionada
    end note

    FiltrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Coordinador</b> solicita filtrar/buscar
    <b>Sistema</b> presenta lista filtrada de convocatorias
    end note

    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Coordinador</b> selecciona una convocatoria
    end note
}

buscarConvocatoria -[#green]-> CONVOCATORIAS_ABIERTAS
note on link
analizarConvocatoria()
end note

buscarConvocatoria -[#green]-> PERFIL
note on link
abrirPerfil()
end note

@enduml
